# [dbIMS]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [dbIMS]    Script Date: 09/03/2024 20:27:09 ******/
CREATE DATABASE [dbIMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbIMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVIDOR_SQL_RAY\MSSQL\DATA\dbIMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbIMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVIDOR_SQL_RAY\MSSQL\DATA\dbIMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbIMS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbIMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbIMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbIMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbIMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbIMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbIMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbIMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbIMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbIMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbIMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbIMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbIMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbIMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbIMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbIMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbIMS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [dbIMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbIMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbIMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbIMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbIMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbIMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbIMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbIMS] SET RECOVERY FULL 
GO
ALTER DATABASE [dbIMS] SET  MULTI_USER 
GO
ALTER DATABASE [dbIMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbIMS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbIMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbIMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dbIMS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbIMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbIMS', N'ON'
GO
ALTER DATABASE [dbIMS] SET QUERY_STORE = OFF
GO

# [dbo].[tbCategory]

In [0]:
USE [dbIMS]
GO

In [0]:
/****** Object:  Table [dbo].[tbCategory]    Script Date: 09/03/2024 20:27:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCategory](
	[catid] [varchar](50) NOT NULL,
	[catname] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[catid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbCustomer]

In [0]:
/****** Object:  Table [dbo].[tbCustomer]    Script Date: 09/03/2024 20:27:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCustomer](
	[cid] [varchar](50) NOT NULL,
	[cname] [varchar](50) NOT NULL,
	[cphone] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbProduct]

In [0]:
/****** Object:  Table [dbo].[tbProduct]    Script Date: 09/03/2024 20:27:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbProduct](
	[pid] [int] IDENTITY(1,1) NOT NULL,
	[pname] [varchar](50) NOT NULL,
	[pqty] [int] NOT NULL,
	[pprice] [int] NOT NULL,
	[pdescription] [varchar](50) NULL,
	[pcategory] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[pid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbUser]

In [0]:
/****** Object:  Table [dbo].[tbUser]    Script Date: 09/03/2024 20:27:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbUser](
	[Username] [varchar](50) NOT NULL,
	[Fullname] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[Phone] [varchar](50) NULL,
 CONSTRAINT [PK_Table] PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbCategory]

In [0]:
INSERT [dbo].[tbCategory] ([catid], [catname]) VALUES (N'232', N'pana')
GO

# [dbo].[tbCustomer]

In [0]:
INSERT [dbo].[tbCustomer] ([cid], [cname], [cphone]) VALUES (N'1', N'Ale', N'232323')
INSERT [dbo].[tbCustomer] ([cid], [cname], [cphone]) VALUES (N'3', N'Raymundo', N'5578294951')
GO

# [dbo].[tbProduct]

In [0]:
SET IDENTITY_INSERT [dbo].[tbProduct] ON 
INSERT [dbo].[tbProduct] ([pid], [pname], [pqty], [pprice], [pdescription], [pcategory]) VALUES (1, N'Pans de pana', 6, 250, N'Pans calientito', N'Ropa deportiva')
SET IDENTITY_INSERT [dbo].[tbProduct] OFF
GO

# [dbo].[tbUser]

In [0]:
INSERT [dbo].[tbUser] ([Username], [Fullname], [Password], [Phone]) VALUES (N'admin', N'admin', N'2002qwert', N'5578294951')
GO

# [dbIMS]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [dbIMS] SET  READ_WRITE 
GO